/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uth.sbmi.usecase3;

import edu.uth.sbmi.swrl.ico.Main;
import edu.uth.sbmi.swrl.ico.UseCaseThree;
import java.awt.FileDialog;
import java.util.List;
import org.apache.commons.lang3.tuple.MutableTriple;
import org.netbeans.api.io.IOProvider;
import org.netbeans.api.io.InputOutput;
import org.netbeans.api.io.OutputColor;
import org.netbeans.api.io.OutputWriter;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//edu.uth.sbmi.usecase3//UC3//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "UC3TopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "edu.uth.sbmi.usecase3.UC3TopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_UC3Action",
        preferredID = "UC3TopComponent"
)
@Messages({
    "CTL_UC3Action=UC3",
    "CTL_UC3TopComponent=Use Case 3 Window",
    "HINT_UC3TopComponent=This is a Use Case 3 window"
})
public final class UC3TopComponent extends TopComponent {
    
    private UseCaseThree u3 = null;

    public UC3TopComponent() {
        initComponents();
        setName(Bundle.CTL_UC3TopComponent());
        setToolTipText(Bundle.HINT_UC3TopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        
        lblAgreement.setVisible(false);
        lblInstances.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUseCase3Model = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInstances = new javax.swing.JButton();
        lblInstances = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgreement = new javax.swing.JButton();
        lblAgreement = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReason = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnOpenFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        txtUseCase3Model.setText(org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.txtUseCase3Model.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnInstances, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.btnInstances.text")); // NOI18N
        btnInstances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstancesActionPerformed(evt);
            }
        });

        lblInstances.setForeground(new java.awt.Color(0, 153, 102));
        org.openide.awt.Mnemonics.setLocalizedText(lblInstances, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.lblInstances.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnAgreement, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.btnAgreement.text")); // NOI18N
        btnAgreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreementActionPerformed(evt);
            }
        });

        lblAgreement.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblAgreement.setForeground(new java.awt.Color(0, 153, 102));
        org.openide.awt.Mnemonics.setLocalizedText(lblAgreement, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.lblAgreement.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnReason, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.btnReason.text")); // NOI18N
        btnReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReasonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.jLabel5.text")); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        org.openide.awt.Mnemonics.setLocalizedText(btnOpenFile, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.btnOpenFile.text")); // NOI18N
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(UC3TopComponent.class, "UC3TopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUseCase3Model, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInstances)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInstances))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgreement)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAgreement))
                            .addComponent(jLabel4)
                            .addComponent(btnReason)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUseCase3Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInstances)
                    .addComponent(lblInstances))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgreement)
                    .addComponent(lblAgreement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstancesActionPerformed
        // TODO add your handling code here:
        
        InputOutput io = IOProvider.getDefault().getIO("Status", false);
        io.reset();
        io.show();
        
        OutputWriter writer = io.getOut();
        
        Main m = new Main();
        m.initUseCaseModelFromPath(this.txtUseCase3Model.getText());
        
        writer.flush();
        writer.println("Ontology model for USE CASE 3 example added...\n");
        
        if(u3 == null){
            u3 = UseCaseThree.getInstance();
        }
        
        u3.addInformedConsentInstances();
        
        writer.println("*** INSTANCES ADDED ***", OutputColor.rgb(255, 0, 0));
        
        writer.close();
        
        lblInstances.setVisible(true); this.btnInstances.setEnabled(false);
        
    }//GEN-LAST:event_btnInstancesActionPerformed

    private void btnAgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreementActionPerformed
        // TODO add your handling code here:
        
        InputOutput io = IOProvider.getDefault().getIO("Status", false);
        io.show();
        OutputWriter writer = io.getOut();
        
        if(u3 == null){
            u3 = UseCaseThree.getInstance();
        }
        
        u3.insertSubjectConsent();
        
        writer.println("*** SUBJECT AGREED ****", OutputColor.rgb(255, 0, 0));
        
        lblAgreement.setVisible(true);
        writer.close(); this.btnAgreement.setEnabled(false);
    }//GEN-LAST:event_btnAgreementActionPerformed

    private void btnReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReasonActionPerformed
        // TODO add your handling code here:
        
        InputOutput io = IOProvider.getDefault().getIO("Status", false); 
        io.show();
        
        if(u3 == null){
            u3 = UseCaseThree.getInstance();
        }
        
        OutputWriter writer = io.getOut();
        
        u3.startReasoner();
        
        writer.println("\n** USE CASE 3 REASONING DEMO **\n");
        
        //What authorization was given as a result of the subject's agreement?
        
        List<MutableTriple<String, String, String>> answer1 = u3.whatIsTheAuthorizationFor();
        
        writer.println("** What authorization was given as a result of the subject's agreement? **", OutputColor.rgb(0, 0, 255));
        writer.println("\t" + "Reasoned answer: ");
        
        for(MutableTriple <String, String, String> triple : answer1){
            writer.println("\t\t" + triple.getLeft() + " > " + triple.getMiddle() + " > " + triple.getRight());
        }
        
        List<MutableTriple<String, String, String>> answer2 = u3.whatAreTheyRestrictedFor();
        
        writer.println("** What are the details of the given authorization? **", OutputColor.rgb(0, 0, 255));
        writer.println("\t" + "Reasoned answer: ");
        
        for(MutableTriple <String, String, String> triple : answer2){
            writer.println("\t\t" + triple.getLeft() + " > " + triple.getMiddle() + " > " + triple.getRight());
        }
        
        writer.close(); this.btnReason.setEnabled(false);
    }//GEN-LAST:event_btnReasonActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        // TODO add your handling code here:
        
        FileDialog fd = new FileDialog((java.awt.Frame) null, "", FileDialog.LOAD);
        fd.setVisible(true);
        String pathFile = fd.getFile();
        
        if(pathFile != null){
            this.txtUseCase3Model.setText(fd.getDirectory()  +pathFile);
        }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.btnReason.setEnabled(true);
        this.btnAgreement.setEnabled(true);
        this.btnInstances.setEnabled(true);
        this.txtUseCase3Model.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgreement;
    private javax.swing.JButton btnInstances;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnReason;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAgreement;
    private javax.swing.JLabel lblInstances;
    private javax.swing.JTextField txtUseCase3Model;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
