/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uth.sbmi.usecase4;

import edu.uth.sbmi.swrl.ico.Main;
import edu.uth.sbmi.swrl.ico.UseCaseFour;
import java.awt.FileDialog;
import java.util.List;
import org.apache.commons.lang3.tuple.MutableTriple;
import org.netbeans.api.*;
import org.netbeans.api.io.IOProvider;
import org.netbeans.api.io.InputOutput;
import org.netbeans.api.io.OutputColor;
import org.netbeans.api.io.OutputWriter;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//edu.uth.sbmi.usecase4//UC4//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "UC4TopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "edu.uth.sbmi.usecase4.UC4TopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_UC4Action",
        preferredID = "UC4TopComponent"
)
@Messages({
    "CTL_UC4Action=UC4",
    "CTL_UC4TopComponent=Use Case 4 Window",
    "HINT_UC4TopComponent=This is a Use Case 4 window"
})
public final class UC4TopComponent extends TopComponent {
    
    private UseCaseFour u4 = null;

    public UC4TopComponent() {
        initComponents();
        setName(Bundle.CTL_UC4TopComponent());
        setToolTipText(Bundle.HINT_UC4TopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        
        lblInstances.setVisible(false);
        lblAgreement.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInstances = new javax.swing.JButton();
        lblInstances = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgreement = new javax.swing.JButton();
        lblAgreement = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnReason = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtUseCase4Model = new javax.swing.JTextField();
        btnOpenFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.jLabel2.text")); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnInstances, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.btnInstances.text")); // NOI18N
        btnInstances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstancesActionPerformed(evt);
            }
        });

        lblInstances.setForeground(new java.awt.Color(0, 153, 102));
        org.openide.awt.Mnemonics.setLocalizedText(lblInstances, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.lblInstances.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnAgreement, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.btnAgreement.text")); // NOI18N
        btnAgreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreementActionPerformed(evt);
            }
        });

        lblAgreement.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblAgreement.setForeground(new java.awt.Color(0, 153, 102));
        org.openide.awt.Mnemonics.setLocalizedText(lblAgreement, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.lblAgreement.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnReason, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.btnReason.text")); // NOI18N
        btnReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReasonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.jLabel8.text")); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtUseCase4Model.setText(org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.txtUseCase4Model.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnOpenFile, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.btnOpenFile.text")); // NOI18N
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(UC4TopComponent.class, "UC4TopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInstances)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstances, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgreement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAgreement, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(btnReason)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUseCase4Model, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUseCase4Model, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInstances)
                    .addComponent(lblInstances))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgreement)
                    .addComponent(lblAgreement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstancesActionPerformed
        // TODO add your handling code here:
        
        InputOutput io = IOProvider.getDefault().getIO("Status", false);
        io.reset();
        io.show();
        
        OutputWriter writer = io.getOut();

        Main m = new Main();
        m.initUseCaseModelFromPath(this.txtUseCase4Model.getText());
        
        writer.flush();
        writer.println("Ontology model for USE CASE 4 example added...\n");
        
        if(u4 == null){
            u4 = UseCaseFour.getInstance();
        }
        
        u4.addInformedConsentInstances();
        
        writer.println("*** INSTANCES ADDED ***", OutputColor.rgb(255, 0, 0));
        
        writer.close();
        
        lblInstances.setVisible(true);
        
        this.btnInstances.setEnabled(false);
    }//GEN-LAST:event_btnInstancesActionPerformed

    private void btnAgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreementActionPerformed
        // TODO add your handling code here:
        
        InputOutput io = IOProvider.getDefault().getIO("Status", false);
        io.show();
        OutputWriter writer = io.getOut();
        
        if(u4 == null){
            u4 = UseCaseFour.getInstance();
        }
        u4.insertSubjectConsent();
        writer.println("*** SUBJECT AGREED ****", OutputColor.rgb(255, 0, 0));
        
        lblAgreement.setVisible(true);
        writer.close();
        
        this.btnAgreement.setEnabled(false);
    }//GEN-LAST:event_btnAgreementActionPerformed

    private void btnReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReasonActionPerformed
        // TODO add your handling code here:
        
        InputOutput io = IOProvider.getDefault().getIO("Status", false); 
        io.show();
        
        if(u4 == null){
            u4 = UseCaseFour.getInstance();
        }
        
        OutputWriter writer = io.getOut();
        u4.startReasoner();
        
        writer.println("\n** USE CASE 4 REASONING DEMO **\n");
        
        //What was the authorization for as a result of subject agreeing?
        writer.println("** What was the authorization for as a result of subject agreeing? **", OutputColor.rgb(0, 0, 255));
        writer.println("\t" + "Reasoned answer: ");
        List<MutableTriple<String, String, String>> answer1 = u4.whatAuthorizationIsGiven();
        for(MutableTriple <String, String, String> triple: answer1){
            writer.println("\t\t" + triple.getLeft() + " > " + triple.getMiddle() + " > " + triple.getRight());
        }
        
        //What are the details of the given authorization?
        writer.println("** What are the details of the given authorization? **", OutputColor.rgb(0, 0, 255));
        writer.println("\t" + "Reasoned answer: ");
        
        List<MutableTriple<String, String, String>> answer2 = u4.whatAreDetailsofAuthorization();
        
        for(MutableTriple<String, String, String> triple: answer2){
            writer.println("\t\t" + triple.getLeft() + " > " + triple.getMiddle() + " > " + triple.getRight());
        }
        
        writer.close();
        
        this.btnReason.setEnabled(false);
    }//GEN-LAST:event_btnReasonActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        // TODO add your handling code here:
        
        FileDialog fd = new FileDialog((java.awt.Frame) null, "", FileDialog.LOAD);
        fd.setVisible(true);
        String pathFile = fd.getFile();
        
        if(pathFile != null){
            this.txtUseCase4Model.setText(fd.getDirectory()  +pathFile);
        }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.btnReason.setEnabled(true);
        this.btnAgreement.setEnabled(true);
        this.btnInstances.setEnabled(true);
        this.txtUseCase4Model.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgreement;
    private javax.swing.JButton btnInstances;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnReason;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAgreement;
    private javax.swing.JLabel lblInstances;
    private javax.swing.JTextField txtUseCase4Model;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }
    
    

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
